version: '2'
services:
  web:
    #dockerd & may need to be ran on the container the first time.
    build: .
    privileged: true
    container_name: manticore_dev
    volumes:
      - './../../:/manticore'
      - /manticore/node_modules/
    ports:
      - "4557:4000"
      - "4848:4646" #nomad ui
    tty: true
